import type { Metadata } from "next";
export const SOCIAL_PAGES = {
  "jev-chat": {
    path: "/language/jev-chat",
    title: "Jev Chat",
    description:
      "Conversation, by choice. Jev decisions, scripted composition, source passages, and verifiable response graphs.",
    category: "JEV-ONLY CONVERSATION",
    steps: ["Ask a question", "Compose with Jev", "Inspect the source"],
    result: "Question → supported reply",
  },
  "clean-room": {
    path: "/agents/clean-room",
    title: "Clean-room rebuild",
    description: "Observed screens. Rebuilt apps. Independent proof.",
    category: "AGENTIC REBUILD",
    steps: [
      "Observe endpoints and screens",
      "Classify and generate",
      "Verify behavior",
    ],
    result: "Target → working rebuild",
  },
  doom: {
    path: "/simulations/doom",
    title: "JevDoom",
    description: "Ten actions. One tiny decision at a time.",
    category: "REACTIVE GAME CONTROL",
    steps: [
      "Capture structured state",
      "Choose a fixed action",
      "Play and compare",
    ],
    result: "Game state → next action",
  },
  reranker: {
    path: "/language/reranker",
    title: "Vector reranker",
    description: "Good matches. Better order.",
    category: "RETRIEVAL & RELEVANCE",
    steps: [
      "Load vector candidates",
      "Score relevance with Jev",
      "Compare the rankings",
    ],
    result: "Shortlist → better order",
  },
  "tool-router": {
    path: "/agents/tool-router",
    title: "Jev tool router",
    description: "Choose the next step. Keep policy in control.",
    category: "GRAPH-BASED ROUTING",
    steps: ["Gather allowed nodes", "Route with Jev", "Apply policy gates"],
    result: "Request → safe next step",
  },
  langchain: {
    path: "/agents/langchain",
    title: "Jev × LangChain",
    description: "A small classifier. A useful tool.",
    category: "TYPESCRIPT INTEGRATION",
    steps: [
      "Invoke a LangChain tool",
      "Classify with Jev",
      "Return a governed route",
    ],
    result: "Tool call → typed decision",
  },
  home: {
    path: "/",
    title: "The Jev playground",
    description: "Find your next small experiment.",
    category: "EXPLORE THE POSSIBILITIES",
    steps: [
      "Language & data",
      "Agents & workflows",
      "Code & governance",
      "Games & simulations",
      "Arcade",
    ],
    result: "One small model. Many clear choices.",
  },
  language: {
    path: "/language",
    title: "Language & data",
    description: "Messy context. Grounded choices.",
    category: "SECTION",
    steps: [
      "Bring text or documents",
      "Offer fixed options",
      "Get a grounded answer",
    ],
    result: "Context → grounded choice",
  },
  agents: {
    path: "/agents",
    title: "Agents & workflows",
    description: "One next step. Policy stays in charge.",
    category: "SECTION",
    steps: [
      "Describe the goal and state",
      "Offer allowed actions",
      "Take the next step",
    ],
    result: "Goal → governed next step",
  },
  governance: {
    path: "/governance",
    title: "Code & governance",
    description: "Typed judgments. Code has the last word.",
    category: "SECTION",
    steps: [
      "Bring a change or constraint",
      "Ask typed questions",
      "Let rules decide",
    ],
    result: "Change → rule-checked verdict",
  },
  simulations: {
    path: "/simulations",
    title: "Games & simulations",
    description: "Small decisions. Visible limits.",
    category: "SECTION",
    steps: ["Read the world state", "Choose one action", "Play it out"],
    result: "State → one action",
  },
  arcade: {
    path: "/arcade",
    title: "Jev Arcade",
    description: "Insert coin. Jev takes the controls.",
    category: "SECTION",
    steps: [
      "Read the game state",
      "Choose a legal move",
      "Score it against chance",
    ],
    result: "Game state → scored move",
  },
  snake: {
    path: "/arcade/snake",
    title: "Jev plays Snake",
    description: "Four directions. One apple at a time.",
    category: "ARCADE",
    steps: ["Read the board", "Choose a direction", "Beat the random baseline"],
    result: "Board → next direction",
  },
  breakout: {
    path: "/arcade/breakout",
    title: "Jev plays Breakout",
    description: "Three paddle moves. Keep the ball alive.",
    category: "ARCADE",
    steps: ["Track the ball", "Move the paddle", "Clear the bricks"],
    result: "Ball → paddle move",
  },
  "meteor-dodge": {
    path: "/arcade/meteor-dodge",
    title: "Jev plays Meteor dodge",
    description: "Five lanes. Nothing but falling rock.",
    category: "ARCADE",
    steps: [
      "Scan the lanes ahead",
      "Change lanes or hold",
      "Survive the field",
    ],
    result: "Lanes → lane change",
  },
  examples: {
    path: "/language/examples",
    title: "Example builder",
    description: "Small experiments. Clear decisions.",
    category: "EXPLORE JEV",
    steps: ["Choose an example", "Define the choices", "See the decision"],
    result: "Ideas → clear outcomes",
  },
  conversation: {
    path: "/language/conversation",
    title: "Conversation lab",
    description: "Find the message worth answering.",
    category: "CONVERSATION ROUTING",
    steps: [
      "Paste a conversation",
      "Compare candidates",
      "Pick the right reply",
    ],
    result: "Context → recipient",
  },
  workflow: {
    path: "/agents/workflow",
    title: "Workflow chat",
    description: "Turn your process into a clear next step.",
    category: "POLICY & PROCESS",
    steps: [
      "Describe the scenario",
      "Apply your process",
      "Choose the next action",
    ],
    result: "Scenario → action",
  },
  "youtube-extract": {
    path: "/language/youtube-extract",
    title: "YouTube extract",
    description: "Original words. Selected passages. Source-linked evidence.",
    category: "EXTRACTIVE TEXT",
    steps: [
      "Fetch existing captions",
      "Score with Jev",
      "Verify at the source",
    ],
    result: "Captions → chronological extract",
  },
  extraction: {
    path: "/language/extraction",
    title: "Document extraction",
    description: "From raw text to grounded answers.",
    category: "CLOSED-SET EXTRACTION",
    steps: ["Find candidate values", "Rank with Jev", "Keep the evidence"],
    result: "Document → structured data",
  },
  memes: {
    path: "/language/memes",
    title: "Meme lab",
    description: "Read the joke. Test the reaction.",
    category: "MEME CLASSIFICATION",
    steps: ["Add a meme", "Review the caption", "Classify the reaction"],
    result: "Meme → prediction",
  },
  "pr-review": {
    path: "/governance/pr-review",
    title: "PR review",
    description: "Focus review on the changes that matter.",
    category: "CLASSIFY & ROUTE",
    steps: [
      "Paste a pull request",
      "Classify each hunk",
      "Review the risky parts",
    ],
    result: "Diff → review decision",
  },
  "proposal-review": {
    path: "/governance/proposal-review",
    title: "Proposal review",
    description: "One proposal. Four questions. Code decides.",
    category: "AGENT REVIEW GATE",
    steps: [
      "Propose one patch",
      "Ask Jev four questions",
      "Decide in code, keep the receipt",
    ],
    result: "Proposal → verdict + receipt",
  },
  "ast-governance": {
    path: "/governance/ast-governance",
    title: "AST-aware governance",
    description: "Understand the change. Trace the impact.",
    category: "CODE & POLICY",
    steps: ["Map affected symbols", "Apply fixed rules", "Review the evidence"],
    result: "Change → informed review",
  },
  gate: {
    path: "/agents/gate",
    title: "Ask gate",
    description: "Ask Jev, or ask a human?",
    category: "QUESTION TRIAGE",
    steps: ["Read the channel", "Gate the question", "Cite the answer"],
    result: "Question → routed or answered",
  },
  microduck: {
    path: "/simulations/microduck",
    title: "MicroDuck arena",
    description: "Nine sensors in. One action out.",
    category: "EMBODIED DECISIONS",
    steps: ["Sense the grid", "Choose one action", "Compare to a baseline"],
    result: "Sensors → next move",
  },
  chess: {
    path: "/simulations/chess",
    title: "Jev attempts chess",
    description: "The wrong tool for the job, on purpose.",
    category: "KNOWN LIMITATION",
    steps: ["Generate legal moves", "Pick one with Jev", "Watch it lose"],
    result: "One decision → no plan",
  },
  "jev-browser-agent": {
    path: "/agents/jev-browser-agent",
    title: "Jev-powered browser agent",
    description: "One goal. One request per step.",
    category: "DYNAMIC ACTION SPACE",
    steps: [
      "Read the element table",
      "Pick operation + target",
      "Verify the outcome",
    ],
    result: "Goal → verified page state",
  },
  "smt-solver": {
    path: "/governance/smt-solver",
    title: "SMT solver lab",
    description: "Fast predictions. Exact verification.",
    category: "JEV + Z3",
    steps: ["Define constraints", "Predict with Jev", "Verify with Z3"],
    result: "Constraints → verified result",
  },
} as const;
export type SocialPage = keyof typeof SOCIAL_PAGES;
export function pageMetadata(key: SocialPage): Metadata {
  const p = SOCIAL_PAGES[key];
  const image = `${p.path === "/" ? "" : p.path}/opengraph-image`;
  return {
    title: `${p.title} · TypeSafe Playground`,
    description: p.description,
    alternates: { canonical: p.path },
    openGraph: {
      title: `${p.title} · TypeSafe AI`,
      description: p.description,
      url: p.path,
      siteName: "TypeSafe AI Playground",
      type: "website",
      images: [
        {
          url: image,
          width: 1200,
          height: 630,
          alt: `TypeSafe AI Playground — ${p.title}. ${p.description}`,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: `${p.title} · TypeSafe AI`,
      description: p.description,
      images: [image],
    },
  };
}
